### PR TITLE
hts-927 custom script for disable anchor on submit

### PR DESCRIPTION
**Pull request by thebailers**

### CODE REVIEW

**Comment by AndyHWChung** [comment]
I can press the cancel button and then the create button - I have an idea on how to fix it though, I'll grab you in a bit...

**Comment by thebailers** [comment]
Ok - sounds good - we can just disable the submit buttons when a cancel button is clicked also?

**Comment by AndyHWChung** [comment]
functionally it works - whether or not it looks like it should visually is not my domain. Is there any chance this could be run by Jean or Nick to see if it looks ok?

**Comment by thebailers** [comment]
Absolutely, will go through it with them.

**Comment by thebailers** [comment]
Checked with Nick and he is happy with everything from a visual perspective.

**Comment by AndyHWChung** [comment]
LGTM

**Pull request merged**
